**1) Making Prediction**

In [0]:
# Example Program y = w * x + b for equation y. w and b is grad=true, x is an input using function
import torch

In [0]:
w = torch.tensor(0.5153, requires_grad=True)
b = torch.tensor(-0.4414, requires_grad=True)

In [0]:
def forward(x):
  y = w * x + b
  return y

In [32]:
x = torch.tensor([[2.0],[7]])
print(x.dim())
forward(x)

2


tensor([[0.5892],
        [3.1657]], grad_fn=<AddBackward0>)

**Completed**

**2) Linear class** 

torch.nn.Module
1) Base calss for all neural network modules
2) Your models should all subclass this class
3) Modules can also contain Modules allowing to nest in a tree structure

In [0]:
import torch
from torch.nn import Linear 

In [39]:
torch.manual_seed(1) # Generates a random values for linear class
model = Linear(in_features=1,out_features=1) # for every prediction make for our linear model for every single output there is a single input
# model is an object
print(model.bias, model.weight) # Bias and weight will be automatically set by manual_seed to the Linear(input(x),weight,bais)


Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [40]:
x = torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)


**Completed**

**3) Custom Modules**

In [0]:
import torch.nn as nn

In [0]:
class LR(nn.Module):                             # Base class of neural network
  def __init__(self, input_size, output_size):   # constructor is automatically called when class object is created
    super().__init__()                           # Calling the Base class
    self.linear = nn.Linear(input_size,output_size) # Linear class (in_feature, out_feature, bais)
  def forward(self, x):                             # forward function
    pred = self.linear(x)
    return pred

In [0]:
torch.manual_seed(1)    # Genearte random values
model = LR(1,1)         # creating object for class LR

In [16]:
x = torch.tensor([2.0]) # x is an input passing to linear
print(model.forward(x))

tensor([0.5891], grad_fn=<AddBackward0>)


**Completed**