**2D Tensor**

In [0]:
import torch

**1) Creating 2D Tensor** 

In [2]:
one_d = torch.arange(0,9)
print(one_d)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [3]:
two_d = one_d.view(3,3)
print("2D tensor :\n", two_d)
print("To see the dimension : ", two_d.dim())

2D tensor :
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
To see the dimension :  2


**To find the element in 2D tensor**

In [4]:
print("First element in 1st row and 1st col :",two_d[0,0])
print("Element from 2nd row and 3rd col     :",two_d[1,2])

First element in 1st row and 1st col : tensor(0)
Element from 2nd row and 3rd col     : tensor(5)


**Creating 3D Tensor**

In [18]:
import numpy as np

a1 = np.arange(18).reshape(3,3,2)
print(a1)
print("3rd Matrix 2nd row and 1st col :",a1[2,1,0])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
3rd Matrix 2nd row and 1st col : 14


In [13]:
three_d = torch.arange(18).view(2,3,3)
print("3D tensor :", three_d)

3D tensor : tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


In [12]:
# Dimension
print("Printing the dimension : ",three_d.dim())

Printing the dimension :  3


In [15]:
# Indexing the value
print("Fetching the value from 1st matrix 2nd row 3rd col :",three_d[0,1,2])

Fetching the value from 1st matrix 2nd row 3rd col : tensor(5)


In [16]:
print("Value from 2nd matrix 3rd row 2nd col :",three_d[1,2,1])

Value from 2nd matrix 3rd row 2nd col : tensor(16)


**Slicing 3D Tensors**

In [20]:
x = torch.arange(18).view(3,2,3)
print("3D Temsor :",x)
print("Prints the value '10' :",x[1,1,1])

3D Temsor : tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])
Prints the value '10' : tensor(10)


In [23]:
# Slicing the 2 matrix
print("Slicing the 2nd Matrix \n :",x[1,0:2,0:3])

Slicing the 2nd Matrix 
 : tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


In [27]:
print(x[1,0:2,0:2])
print(x[1,0:2,1:3])
print("13 and 14 \n ",x[2,0:1,1:3])

tensor([[ 6,  7],
        [ 9, 10]])
tensor([[ 7,  8],
        [10, 11]])
13 and 14 
  tensor([[13, 14]])


In [29]:
print(x[2,:,:])

tensor([[12, 13, 14],
        [15, 16, 17]])


**Matrix Multiplication**

In [32]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
print(mat_a)
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
print(mat_b)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


In [33]:
torch.matmul(mat_a,mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [34]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])